/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 parkchester.gltf --transform --simplify 
Files: parkchester.gltf [39.12MB] > /Users/lvillarreal/Desktop/stuy-town/static/parkchester-transformed.glb [1.04MB] (97%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/parkchester-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <lineSegments geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
      <lineSegments geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} />
      <lineSegments geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} />
      <mesh geometry={nodes.mesh_3.geometry} material={nodes.mesh_3.material} />
    </group>
  )
}

useGLTF.preload('/parkchester-transformed.glb')
