/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 riverton.gltf --transform --simplify 
Files: riverton.gltf [801.84KB] > /Users/lvillarreal/Desktop/stuy-town/static/riverton-transformed.glb [24.7KB] (97%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/riverton-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <lineSegments geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
      <lineSegments geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} />
      <lineSegments geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} />
      <mesh geometry={nodes.mesh_3.geometry} material={nodes.mesh_3.material} />
    </group>
  )
}

useGLTF.preload('/riverton-transformed.glb')
