/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 stuy-town.gltf --transform --simplify 
Files: stuy-town.gltf [7.45MB] > /Users/lvillarreal/Desktop/stuy-town/static/stuy-town-transformed.glb [64.11KB] (99%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/stuy-town-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
}

useGLTF.preload('/stuy-town-transformed.glb')
